#!/bin/bash

# Author: Nick Baynham
# Description: Check Connectivity
# Created On: July 6, 2020

hosts=./hosts
for host in $(cat $hosts)
do
  ping -c1 $host &> /dev/null
  if [ $? -eq 0 ]; then
    echo Ok
  else
    echo No Response
  fi
done
